- hosts: remote
  gather_facts: false
  vars:
    src: test1.txt
    dest: /home/ansible_user/test1.txt
  tasks:
  - name : copy file to remote server
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"

